/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catedra2;

import Base_Datos.ConexionMySQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author azapata
 */
public class Mantenedor extends javax.swing.JFrame {

    /**
     * Creates new form Mantenedor
     */
    DefaultTableModel modelo;
    int fila = -1;

    public Mantenedor() {
        initComponents();
        inhabilitar();
        
        Regiones rg = new Regiones();
        rg.cargarR(cmbRegion);
        
        Ciudades ci = new Ciudades();
        ci.cargarCi(cmbCiudad);
        
        Comunas cm = new Comunas();
        cm.cargarCm(cmbComuna);
        
        Sexo se = new Sexo();
        se.cargarS(cmbSexo);
//        Sexo();
  //      region();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtRut = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        txtDv = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbComuna = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbRegion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Grilla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        label1.setText("Rut");

        label2.setText("Dv");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDv)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtRut.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnGrabar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Nombre");

        jLabel2.setText("Paterno");

        jLabel3.setText("Materno");

        jLabel4.setText("Sexo");

        cmbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexoActionPerformed(evt);
            }
        });

        jLabel5.setText("Comuna");

        cmbComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbComunaActionPerformed(evt);
            }
        });

        jLabel6.setText("Ciudad");

        jLabel7.setText("Region");

        jLabel8.setText("Direccion");

        jLabel9.setText("Telefono");

        jLabel10.setText("Celular");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(37, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cmbSexo.getAccessibleContext().setAccessibleName("");

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        Grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Grilla);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String valor = txtRut.getText();
        CargarTablaEmpleados(valor);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        String rut1;
        String sSQL = "";
        String mensaje = "";
        rut1 = txtRut.getText();

        sSQL = "DELETE FROM uhvida where rut = ?";
        mensaje = "Datos eliminados correctamente.";
        habilitar();
        try {
            PreparedStatement pst = cn.prepareStatement(sSQL);
            pst.setString(1, rut1);

            int n = pst.executeUpdate();

            if (n > 0) {
                JOptionPane.showMessageDialog(null, mensaje);
                CargarTablaEmpleados("");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // TODO add your handling code here:
        if (!ValidaRut.isValidRut(txtRut.getText(), txtDv.getText())) {
            JOptionPane.showMessageDialog(null, "Rut indicado no es valido: " + txtRut.getText() + "-" + txtDv.getText() + ".", "Buscar Rut", JOptionPane.ERROR_MESSAGE);
            habilitar();
            return;
        }
        if (txtNombre.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre antes de guardar... intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            txtNombre.requestFocus(true);
            return;
        }
        if (txtPaterno.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el apellido paterno antes de guardar... intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            txtPaterno.requestFocus(true);
            return;
        }
        if (txtMaterno.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el apellido materno antes de guardar... intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            txtMaterno.requestFocus(true);
            return;
        }
        if (txtDireccion.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la direccion antes de guardar... intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            txtDireccion.requestFocus(true);
            return;
        }
        //int IndReg= cmbCiudad.getSelectedIndex();
        //if (IndReg<=0){
        //    JOptionPane.showMessageDialog(null, "Debe seleccionar la ciudad antes de guardar... intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        //    cmbCiudad.requestFocus(true);
        //    return;
        //}
        //int IndCom = cmbComuna.getSelectedIndex();
        //if (IndCom<=0){
        //    JOptionPane.showMessageDialog(null, "Debe seleccionar la comuna antes de guardar... intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        //    cmbComuna.requestFocus(true);
        //    return;
        //}
        if (txtTelefono.getText().length() > 0) {
            try {
                int Valor2 = Integer.parseInt(txtTelefono.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "El numero de telefono es demasiado grande o no es un numero... Intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                txtTelefono.setText(null);
                txtTelefono.requestFocus();
                return;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Ingreso un numero muy grande para el telefono... Intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                txtTelefono.setText(null);
                txtTelefono.requestFocus();
                return;
            }
        }
        if (txtCelular.getText().length() > 0) {
            try {
                int Valor3 = Integer.parseInt(txtCelular.getText());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "El numero de celular es demasiado grande o no es un numero... Intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                txtCelular.setText(null);
                txtCelular.requestFocus();
                return;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Ingreso un numero muy grande para el celular... Intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                txtCelular.setText(null);
                txtCelular.requestFocus();
                return;
            }
        }
        //valido el largo de los campos
        if (txtNombre.getText().length() > 50) {
            JOptionPane.showMessageDialog(null, "El nombre es muy largo, solo se permiten 50 caracteres... escribio " + txtNombre.getText().length() + ", intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            txtNombre.requestFocus(true);
            return;
        }
        if (txtPaterno.getText().length() > 50) {
            JOptionPane.showMessageDialog(null, "El apellido paterno es muy largo, solo se permiten 50 caracteres... escribio " + txtNombre.getText().length() + ", intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            txtPaterno.requestFocus(true);
            return;
        }
        if (txtMaterno.getText().length() > 50) {
            JOptionPane.showMessageDialog(null, "El apellido materno es muy largo, solo se permiten 50 caracteres... escribio " + txtNombre.getText().length() + ", intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            txtMaterno.requestFocus(true);
            return;
        }
        if (txtDireccion.getText().length() > 120) {
            JOptionPane.showMessageDialog(null, "El campo direccion es muy largo, solo se permiten 50 caracteres... escribio " + txtNombre.getText().length() + ", intentelo nuevamente.", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            txtDireccion.requestFocus(true);
            return;
        }
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        //String rut1, dv1, nom, pat, mat, sex, dir, reg, com, ciu, tel, cel;
        String rut1, dv1, nom, pat, mat, dir, tel, cel;
        String sSQL = "";
        String mensaje = "";
        rut1 = txtRut.getText();
        dv1 = txtDv.getText();
        nom = txtNombre.getText();
        pat = txtPaterno.getText();
        mat = txtMaterno.getText();
        dir = txtDireccion.getText();
        //sex = cmbSexo.getSelectedItem().toString();
        //reg = cmbRegion.getSelectedItem().toString();
        //com = cmbComuna.getSelectedItem().toString();
        //ciu = cmbCiudad.getSelectedItem().toString();
        tel = String.valueOf(txtTelefono.getText());
        cel = String.valueOf(txtCelular.getText());

        int RutP = Integer.parseInt(rut1);

        if (ExisteRut(RutP)) {

            sSQL = "UPDATE uhvida SET ";
            sSQL = sSQL + "nombre='" + nom + "',";
            sSQL = sSQL + "paterno='" + pat + "',";
            sSQL = sSQL + "materno='" + mat + "',";
            //sSQL=sSQL+"sexo='"+sex+"',";
            sSQL = sSQL + "direccion='" + dir + "',";
            //sSQL=sSQL+"id_region='"+reg+"',";
            //sSQL=sSQL+"id_comuna='"+com+"',";
            //sSQL=sSQL+"id_ciudad='"+ciu+"',";            
            sSQL = sSQL + "telefono=" + tel + ",";
            sSQL = sSQL + "celular=" + cel + " ";
            sSQL = sSQL + "where rut=" + RutP;

            mensaje = "Los datos se han Modificado de Manera Satisfactoria...";

            try {
                PreparedStatement pst = cn.prepareStatement(sSQL);

                int n = pst.executeUpdate();

                if (n > 0) {
                    JOptionPane.showMessageDialog(null, mensaje);
                    CargarTablaEmpleados("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

        } else {

            sSQL = "INSERT INTO uhvida (rut, dv, nombre, paterno, materno, id_sexo, direccion, id_region, id_comuna, id_ciudad, telefono, celular)"
                    + "VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            mensaje = "Datos insertados correctamente.";

            try {
                PreparedStatement pst = cn.prepareStatement(sSQL);
                pst.setString(1, rut1);
                pst.setString(2, dv1);
                pst.setString(3, nom);
                pst.setString(4, pat);
                pst.setString(5, mat);
                pst.setString(6, "1");
                pst.setString(7, dir);
                pst.setString(8, "1");
                pst.setString(9, "1");
                pst.setString(10, "1");
                pst.setString(11, tel);
                pst.setString(12, cel);

                int n = pst.executeUpdate();

                if (n > 0) {
                    JOptionPane.showMessageDialog(null, mensaje);
                    CargarTablaEmpleados("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }


    }//GEN-LAST:event_btnGrabarActionPerformed

    private void cmbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbSexoActionPerformed

    /**void region() {
        String sSQL = "select * from region";
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        try {
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = (ResultSet) st.executeQuery(sSQL);

            cmbRegion.addItem("Seleciione Region");
            while (rs.next()) {
                cmbRegion.addItem(rs.getNString("region"));
            }
            rs.close();
        } catch (Exception ex) {

        }

    }

    void Sexo() {

        String sSQL = "select * from sexo";
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();
        try {
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = (ResultSet) st.executeQuery(sSQL);

            cmbSexo.addItem("Seleciione Sexo");
            while (rs.next()) {
                cmbSexo.addItem(rs.getNString("sexo"));
            }
            rs.close();
        } catch (Exception ex) {

        }
    }
**/
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void GrillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrillaMouseClicked
        // TODO add your handling code here:
        fila = Grilla.rowAtPoint(evt.getPoint());
        if (fila > -1) {
            txtRut.setText(String.valueOf(Grilla.getValueAt(fila, 0)));
            txtDv.setText(String.valueOf(Grilla.getValueAt(fila, 1)));
            txtNombre.setText(String.valueOf(Grilla.getValueAt(fila, 2)));
            txtPaterno.setText(String.valueOf(Grilla.getValueAt(fila, 3)));
            txtMaterno.setText(String.valueOf(Grilla.getValueAt(fila, 4)));
            //cmbSexo.setText(String.valueOf(Grilla.getValueAt(fila, 5)));
            txtDireccion.setText(String.valueOf(Grilla.getValueAt(fila, 6)));
            //cmbComuna.setText(String.valueOf(Grilla1.getValueAt(fila, 7)));
            //cmbCiudad.setText(String.valueOf(Grilla1.getValueAt(fila, 8)));             
            //cmbRegion.setText(String.valueOf(Grilla1.getValueAt(fila, 9)));
            txtTelefono.setText(String.valueOf(Grilla.getValueAt(fila, 10)));
            txtCelular.setText(String.valueOf(Grilla.getValueAt(fila, 11)));
        }
    }//GEN-LAST:event_GrillaMouseClicked

    private void cmbComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbComunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbComunaActionPerformed

    public static Boolean ExisteRut(int Rut) {
        String sSQL = "select * from uhvida where rut=" + Rut;
        try {
            //clsConectarDB cnn = new clsConectarDB();
            ConexionMySQL mysql = new ConexionMySQL();
            Connection cn = mysql.Conectar();
            //ResultSet rs = cn.EjecutaQuery(sql);
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = (ResultSet) st.executeQuery(sSQL);
            int ContReg = 0;
            while (rs.next()) {
                ContReg++;
            }
            if (ContReg > 0) {
                return true;
            } else {
                return false;
            }
        } catch (Exception ex) {

        }
        return false;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenedor().setVisible(true);
            }
        });
    }

    void CargarTablaEmpleados(String valor) {
        String[] titulos = {"Rut", "Dv", "Nombre", "Paterno", "Materno", "Sexo", "Direccion", "Region", "Comuna", "Ciudad", "Telefono", "Celular"};
        String[] registro = new String[12];
        String sSQL = "";
        modelo = new DefaultTableModel(null, titulos);

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.Conectar();

        sSQL = "SELECT u.rut, u.dv, u.nombre, u.paterno, u.materno, s.sexo, u.direccion,  "
                + "r.region,c.comuna, ci.ciudad, u.telefono, u.celular "
                + "FROM uhvida u, comuna c, ciudad ci, region r, sexo s "
                + "WHERE u.id_comuna = c.id_comuna "
                + "and u.id_region = r.id_region "
                + "and u.id_ciudad = ci.id_ciudad "
                + "and s.id_sexo = u.id_sexo "
                + "and rut LIKE '%" + valor + "%'";
        try {
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = (ResultSet) st.executeQuery(sSQL);

            while (rs.next()) {
                registro[0] = rs.getString("rut");
                registro[1] = rs.getString("dv");
                registro[2] = rs.getString("nombre");
                registro[3] = rs.getString("paterno");
                registro[4] = rs.getString("materno");
                registro[5] = rs.getString("sexo");
                registro[6] = rs.getString("direccion");
                registro[7] = rs.getString("region");
                registro[8] = rs.getString("comuna");
                registro[9] = rs.getString("ciudad");
                registro[10] = rs.getString("telefono");
                registro[11] = rs.getString("celular");
                modelo.addRow(registro);
            }
            Grilla.setModel(modelo);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    void limpiar() {
        txtRut.setText("");
        txtDv.setText("");
        txtNombre.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCelular.setText("");

    }

    void habilitar() {
        txtRut.setEnabled(true);
        txtDv.setEnabled(true);
        cmbSexo.setEnabled(true);
        txtNombre.setEnabled(true);
        txtPaterno.setEnabled(true);
        txtMaterno.setEnabled(true);
        txtPaterno.setEnabled(true);
        txtMaterno.setEnabled(true);
        txtDireccion.setEnabled(true);
        cmbComuna.setEnabled(true);
        cmbCiudad.setEnabled(true);
        cmbRegion.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtCelular.setEnabled(true);
        txtRut.setText("");
        txtDv.setText("");
        txtNombre.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCelular.setText("");
        btnGrabar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        btnBuscar.setEnabled(true);
        txtRut.requestFocus();
    }

    void inhabilitar() {
        txtRut.setEnabled(false);
        txtDv.setEnabled(false);
        cmbSexo.setEnabled(false);
        txtNombre.setEnabled(false);
        txtPaterno.setEnabled(false);
        txtMaterno.setEnabled(false);
        txtPaterno.setEnabled(false);
        txtMaterno.setEnabled(false);
        txtDireccion.setEnabled(false);
        cmbComuna.setEnabled(false);
        cmbCiudad.setEnabled(false);
        cmbRegion.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtCelular.setEnabled(false);
        txtRut.setText("");
        txtDv.setText("");
        txtNombre.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCelular.setText("");
        btnGrabar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnLimpiar.setEnabled(false);
        btnBuscar.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grilla;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Ciudades> cmbCiudad;
    private javax.swing.JComboBox<Comunas> cmbComuna;
    private javax.swing.JComboBox<Regiones> cmbRegion;
    private javax.swing.JComboBox<Sexo> cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDv;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
